language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - XCACHE_VERSION=3.2.0
  - XCACHE_VERSION=3.1.2
  - XCACHE_VERSION=3.0.4
  - XCACHE_VERSION=2.0.1
  - XCACHE_VERSION=1.3.2

before_install:
  - wget http://xcache.lighttpd.net/pub/Releases/${XCACHE_VERSION}/xcache-${XCACHE_VERSION}.tar.gz
  - wget http://xcache.lighttpd.net/pub/Releases/${XCACHE_VERSION}/xcache-${XCACHE_VERSION}.tar.gz.md5.txt
  - md5sum -c xcache-${XCACHE_VERSION}.tar.gz.md5.txt
  - tar xf xcache-${XCACHE_VERSION}.tar.gz
  - pushd xcache-${XCACHE_VERSION}
  - phpize
  - ./configure
  - make
  - make install
  - popd
  - printf "extension=xcache.so\nxcache.var_size=1M" > xcache.ini
  - phpenv config-add xcache.ini

install:
  - composer install

script:
  - composer test
