language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - wget http://xcache.lighttpd.net/pub/Releases/3.2.0/xcache-3.2.0.tar.gz
  - tar xf xcache-3.2.0.tar.gz
  - pushd xcache-3.2.0
  - phpize
  - ./configure
  - make
  - sudo make install
  - popd
  - printf "extension=xcache.so\nxcache.var_size=1M" > xcache.ini
  - phpenv config-add xcache.ini
