language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y php5-xcache
  - printf "extension=xcache.so\nxcache.var_size=1M" > xcache.ini
  - phpenv config-add xcache.ini
